### ISSUE TITLE
[9.0] mrp_plan_wizard: Crash at printing

### ISSUE THREAD

**Issue by MouTio** [wt-io-it/odoo-addons#11]
If you try to print, Odoo crashes with this exception:

```
Odoo Server Error
Traceback (most recent call last):
  File "/etc/odoo/server/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/etc/odoo/server/openerp/http.py", line 525, in response_wrap
    response = f(*args, **kw)
  File "/etc/odoo/server/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=data, context=context)
  File "/etc/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/etc/odoo/server/addons/report/models/report.py", line 181, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/etc/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/etc/odoo/server/addons/report/models/report.py", line 147, in get_html
    return self.render(cr, uid, [], report.report_name, docargs, context=context)
  File "/etc/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/etc/odoo/server/addons/report/models/report.py", line 123, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/etc/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/etc/odoo/server/addons/website/models/ir_ui_view.py", line 166, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/etc/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/etc/odoo/server/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/etc/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_ui_view.py", line 1087, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/etc/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 254, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 448, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 426, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 371, in render_tag_raw
    inner = self.eval_str(template_attributes["raw"], qwebcontext)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 203, in eval_str
    val = self.eval(expr, qwebcontext)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 195, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 192, in eval
    return qwebcontext.safe_eval(expr)
  File "/etc/odoo/server/openerp/addons/base/ir/ir_qweb.py", line 104, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/etc/odoo/server/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
QWebException: "'NoneType' object is not callable" while evaluating
"translate_doc(doc_id, doc_model, 'create_uid.lang', 'mrp_plan_wizard.mrp_plan_list_document')"
```

**Comment by MouTio** [comment]
Fixed with this PR: https://github.com/wt-io-it/odoo-addons/pull/12
