### ISSUE TITLE
ImportError: No module named addons.decimal_precision 

### ISSUE THREAD

**Issue by ConfiserieJonas** [wt-io-it/odoo-addons#2]
When trying to install the modules I have the following errors
 Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 719, in install_from_urls
    self.update_list(cr, uid, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/opt/odoo/odoo-server/openerp/http.py", line 1317, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/account_product_gross_net/__init__.py", line 1, in <module>
    import models
  File "/opt/odoo/.local/share/Odoo/addons/8.0/account_product_gross_net/models/__init__.py", line 1, in <module>
    import product
  File "/opt/odoo/.local/share/Odoo/addons/8.0/account_product_gross_net/models/product.py", line 6, in <module>
    import addons.decimal_precision as dp
ImportError: No module named addons.decimal_precision

It seems I am missing the module addons.decimal_precision
The module decimal_precision is installed is this the same ?

**Comment by kennyMC** [comment]
i fixed this error here:
https://github.com/kennyMC/odoo-addons/commit/9d409c627249cd2659a83f424e9dd9f76e6f316d

**Comment by wtaferner** [comment]
Thank you for reporting. It has been fixed in 18b1104.
